apiVersion: v1
kind: List
items:

# a scoped router
- apiVersion: v1
  kind: Pod
  metadata:
    name: scoped-router
    labels:
      test: scoped-router
  spec:
    containers:
    - name: router
      image: openshift/origin-haproxy-router
      env:
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      args: ["--namespace=$(POD_NAMESPACE)", "--loglevel=4", "--labels=select=first"]
      hostNetwork: false
      ports:
      - containerPort: 80
      - containerPort: 443
      - containerPort: 1936
        name: stats
        protocol: TCP
    serviceAccountName: default


# ensure the router can access routes and endpoints
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: system-router
  subjects:
  - kind: ServiceAccount
    name: default
  roleRef:
    name: system:router

# two routes that differ only by their labels and names
- apiVersion: v1
  kind: Route
  metadata:
    name: route-1
    labels:
      test: router
      select: first
  spec:
    host: hello-openshift.com
    to:
      name: endpoints
    ports:
    - targetPort: 8080
    tls:
    - termination: edge
    - certificate: -----BEGIN CERTIFICATE-----\nMIIDVDCCAjwCCQDenfbjF48d7zANBgkqhkiG9w0BAQUFADBsMQswCQYDVQQGEwJV\nUzELMAkGA1UECAwCQ0ExFjAUBgNVBAcMDU1vdW50YWluIFZpZXcxDDAKBgNVBAoM\nA09TMzEMMAoGA1UECwwDRW5nMRwwGgYDVQQDDBNoZWxsby1vcGVuc2hpZnQuY29t\nMB4XDTE2MDUyNDE3NTg1N1oXDTE3MDUyNTE3NTg1N1owbDELMAkGA1UEBhMCVVMx\nCzAJBgNVBAgMAkNBMRYwFAYDVQQHDA1Nb3VudGFpbiBWaWV3MQwwCgYDVQQKDANP\nUzMxDDAKBgNVBAsMA0VuZzEcMBoGA1UEAwwTaGVsbG8tb3BlbnNoaWZ0LmNvbTCC\nASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANImUA2wzC6CWn/dVJQagsvb\nLEe32EuG8cuLye+GVkDnoCPkre8s/cUjMC5F447IpLuJc/3paKXr+zM5pXh0rjra\nRD1N0WOghw+Kp6T06xQsm3VFTG6Sg7IX7ScqLnIKp5LgNXNkc58DMEx30qwu60FI\nFXZb6LhPtsOQbE3j+x07XIqrAVIUrXYuHo5zawtcwm7EG7lZ65tQJxuYNAz/0I2o\nENSfpZzbMqMtTYaAzO59Y5ehN6NrB0tEtNyAb8ZrmG2JCkZ5T6UFpLv6p46lKO01\nAACqHqeu4vk1/UE+dAOvgS4e/M2rMHa3khd2mpiGKLqOXYRdHEX9d05jKARpoPUC\nAwEAATANBgkqhkiG9w0BAQUFAAOCAQEAWrOQqbMv0Rc8M99H53CTWEj1EXkpHNlF\nUISFHyLh4ZR15Q4tQvjs8U2fz8d65ei+zAv9tgAod2wC8SqoTkK5YZ5/rNa+UxGW\ngE2CTdqUWpxZIUDCwE6E8S4tsgkr7x7X5jGZ7npSLGWb4/JZ8QjqdQz/a47KUg3a\ns0Do4FIQMdwK2MXYfFHc3Wpnb5+ggzuaNIfeIgUvyhddnC8MiAVi8SXWnj7qC301\nn4dEbt4TZ2AbAGWOounCvZZiTi3aqjXsDvtex7w+Te1CijhiMXISUs0gR2+G6hHu\nQmmJElX6YtFzHVLQPPSBARS8DInhA11le3jZUHy9ZjO2y3v9FP9sIw==\n-----END CERTIFICATE-----\n
    - key: -----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEA0iZQDbDMLoJaf91UlBqCy9ssR7fYS4bxy4vJ74ZWQOegI+St\n7yz9xSMwLkXjjsiku4lz/elopev7MzmleHSuOtpEPU3RY6CHD4qnpPTrFCybdUVM\nbpKDshftJyoucgqnkuA1c2RznwMwTHfSrC7rQUgVdlvouE+2w5BsTeP7HTtciqsB\nUhStdi4ejnNrC1zCbsQbuVnrm1AnG5g0DP/QjagQ1J+lnNsyoy1NhoDM7n1jl6E3\no2sHS0S03IBvxmuYbYkKRnlPpQWku/qnjqUo7TUAAKoep67i+TX9QT50A6+BLh78\nzaswdreSF3aamIYouo5dhF0cRf13TmMoBGmg9QIDAQABAoIBAQC9krJEp2iJzC23\niwHxWLkFDQI08DO+bk1RQRk5agYFJu3fczs0t3F1lPixxXoyI+32/1gThatRgj9p\nRmdu8lL55EwKwVhSd01fR8VTmV03JcZXU9xPIvyKe+sDmZmsZtAkPv34ynVCzK2V\nTcJOcUTn7w7tZpvZKI/Ge1I4MaEmC/OQms1Gota6e5gn9AHvKDetxFdooT9VAPxZ\nOWgs9KNV+YbqmkJPyzAWkzC1WC259p7tcKu4OEoEno76KBmXlILQtmXuc6/TPsFW\nOzfiSZVUUUu4w1rMRs47g2A29lm8vbhumbcY/ZsFb3ApS7NThFQm2aPTRZDCDhXX\nY4GD0J9BAoGBAPXW28zMBsTIB64zXsfvNXCxwB29q9KOPDTAdiLZ6Sv+ACpSXBM9\nXuM9W3gmMdHx8c1Bj6DIyvDBzdJQySEQR5KQtGunsam/Gk4oJrIXdU3nRY8ITfrw\ndbLynDwGuK7+9WRAOlKXG/rWSxfYFepMUj5hKEPQQAt9G6XbAkLZnrqnAoGBANrV\n1ZafNBhbw0ikMMrdVuMRWZpv1HIw5VBCX8rH2joYx7b2g/Lo4l0/JUmqQ5rQC//E\nXmJeUIqrGUSuiN8q4/XnqwVqOMtZoLNlE7ULGXG47vTFlGG5teuiM+10n1T5ikkU\nDwqS5J4pSAKyZ7NrNVZQDiJglksEv1m0z26XsicDAoGAaM2vKJC2Nf/cnlwSBQQq\ncR+l+kfYz0uJySdfdZ4WdIW1RlWUITOhlxiaPQ9zX8BYSBuyAmZ3dcn5V7bO98R7\n7rS35ck4yVfJ/BXL4VJ01MBKfB6bN+Z5Fs+s4T4wT5IrxRBIjNsUt4vRuZmKRjdB\nPIyo4LgQBZXRSpSiUyN5MrMCgYBZCLcl2RAw+OSzIVpYr0UyjVSPaQBelVY3GUow\nDq/TA1H+Nr3ojqfKmG5rUkK/MfYv0Y01KHpMcOCO+RPm+GRXIDKMuXLyCT1Av9cM\nyb9IbZ2LKPf96rkBbbUC33gT8pM4uFiGTM2HK/SIZF2cufmxbFDT28hKLVxM+yuK\nK13oUQKBgBszHuUiftUTZhNbS3lK3lzte2xMFts1swza27qDlQkQZnVDVdsyOaiu\nPaxmoB5b0fnHKeBOS18BakDurlFPiYYcjw0zr7ZejPy95LEDBa5uQ7DFfN67im0Q\nwNHI7AeXK2Itywzq1btY9FE/KFoC1bc6zZ/ikyql/0blMdmP1rFK\n-----END RSA PRIVATE KEY-----\n



# a service to be routed to
- apiVersion: v1
  kind: Service
  metadata:
    name: endpoints
    labels:
      test: router
  spec:
    selector:
      test: router
      endpoints: router
    ports:
    - port: 8080

# a pod that serves a response
- apiVersion: v1
  kind: Pod
  metadata:
    name: endpoint-1
    labels:
      test: router
      endpoints: router
  spec:
    containers:
    - name: test
      image: openshift/hello-openshift
      # image: openshift/deployment-example:v1
      ports:
      - containerPort: 8080
        name: http
      - containerPort: 100
        protocol: UDP
