
apiVersion: v1
kind: Pod
metadata:
  name: egress-http-proxy
  labels:
    name: egress-http-proxy
  annotations:
    pod.network.openshift.io/assign-macvlan: "true"
spec:
  initContainers:
  - name: egress-init-container
    image: openshift3/ose-egress-router
    env:
    - name: EGRESS_SOURCE
      value: 172.18.0.177
    - name: EGRESS_GATEWAY
      value: 172.18.0.1
    - name: EGRESS_DESTINATION
      value: 216.58.217.110
    - name: EGRESS_ROUTER_MODE
      value: init
    securityContext:
      privileged: true
  containers:
  - name: egress-proxy-container
    image: aosqe/pod-for-ping
    env:
    - name: EGRESS_HTTP_PROXY_DESTINATION
      value: |
        protocol: TCP
        port: 80
