apiVersion: v1
kind: Pod
metadata:
  name: egressrouter-redirect
  labels:
    name: egressrouter-redirect
  annotations:
    pod.network.openshift.io/assign-macvlan: "true"
spec:
  initContainers:
  - name: egress-router-setup
    imagePullPolicy: IfNotPresent
    image: openshift3/ose-egress-router
    securityContext:
      privileged: true
    env:
    - name: EGRESS_SOURCE
      value: 172.17.0.9
    - name: EGRESS_GATEWAY
      value: 172.17.0.1
    - name: EGRESS_DESTINATION 
      value: | 
        80 tcp www.yahoo.com
        8080 udp www.cisco.com
        8000 tcp www.redhat.com 80
        8443 udp www.google.com 443
        www.facebook.com
    - name: EGRESS_ROUTER_MODE
      value: init
  containers:
  - name: egressrouter-redirect
    image: openshift3/ose-pod
    
