apiVersion: v1
kind: Pod
metadata:
  name: egress-redirect
  labels:
    name: egress-redirect
  annotations:
    pod.network.openshift.io/assign-macvlan: "true"
spec:
  initContainers:
  - name: egress-router-setup
    imagePullPolicy: IfNotPresent
    image: openshift3/ose-egress-router
    securityContext:
      privileged: true
    env:
    - name: EGRESS_SOURCE
      value: 172.17.0.9
    - name: EGRESS_GATEWAY
      value: 172.17.0.1
    - name: EGRESS_DESTINATION 
      value: | 
        80   tcp www.test.com 
        8443 tcp www.yahoo.com 443
    - name: EGRESS_ROUTER_MODE
      value: init
  containers:
  - name: egress-redirect
    
