apiVersion: v1
kind: Pod
metadata:
  name: egress-redirect
  labels:
    name: egress-redirect
  annotations:
    pod.network.openshift.io/assign-macvlan: "true"
spec:
  initContainers:
  - name: egress-router
    image: openshift3/ose-egress-router
    securityContext:
      privileged: true
    env:
    - name: EGRESS_SOURCE
      value: 10.240.0.69
    - name: EGRESS_GATEWAY
      value: 10.240.0.1
    - name: EGRESS_DESTINATION 
      value: 10.240.0.65
    - name: EGRESS_ROUTER_MODE
      value: init
  containers:
  - name: egressrouter-redirect
    image: openshift3/ose-pod
    
    
